"use strict";
const fs=require("node:fs"),path=require("node:path"),os=require("node:os"),assert=require("node:assert/strict"),{execFileSync,fork}=require("node:child_process"),{performance}=require("node:perf_hooks");
const {client,freePort}=require("../../test/helpers"),ROOT=path.join(__dirname,"../.."),OUT=process.argv[2];assert.ok(OUT);fs.mkdirSync(OUT,{recursive:true});
const work=fs.mkdtempSync(path.join(os.tmpdir(),"nc-io-bench-")),meter=require("./io-meter");
const percentile=(a,p)=>[...a].sort((x,y)=>x-y)[Math.min(a.length-1,Math.ceil(a.length*p)-1)];
function summary(samples){const keys=new Set(samples.flatMap(x=>Object.keys(x.io||{})));return{samples:samples.length,latencyMs:{p50:percentile(samples.map(x=>x.ms),.5),p95:percentile(samples.map(x=>x.ms),.95),max:Math.max(...samples.map(x=>x.ms))},meanNodeFileApi:Object.fromEntries([...keys].map(k=>[k,samples.reduce((n,x)=>n+(x.io?.[k]||0),0)/samples.length]))};}
function storeCase(code,label,size,remove){const samples=[];for(let n=0;n<(remove?5:35);n++){
 const d=path.join(work,label+'-'+n);fs.mkdirSync(d);const users={users:Array.from({length:size?20:1},(_,i)=>({name:i===0?'admin':'u'+i,hash:'synthetic-fixed-hash'}))},sessions=Object.fromEntries(Array.from({length:size?200:1},(_,i)=>['synthetic-session-'+i,{user:'admin',expires:1900000000000}]));
 if(remove)users.users.push({name:'bob',hash:'synthetic-fixed-hash'});fs.writeFileSync(path.join(d,'users.json'),JSON.stringify(users,null,2));fs.writeFileSync(path.join(d,'sessions.json'),JSON.stringify(sessions,null,2));
 if(remove){for(const dir of ['config','backup','icons','spaces-guard','wallpapers'])fs.mkdirSync(path.join(d,dir));fs.mkdirSync(path.join(d,'icons/bob'));for(let i=0;i<64;i++)fs.writeFileSync(path.join(d,'icons/bob',i+'.png'),Buffer.alloc(128*1024,i));}
 const {createAuthStore}=require(code),store=createAuthStore(d,{users:x=>x&&Array.isArray(x.users),sessions:x=>x&&typeof x==='object'});meter.reset();const start=performance.now();store.commit(remove?{...users,users:users.users.filter(x=>x.name!=='bob')}:users,sessions,remove?'bob':null);const sample={ms:performance.now()-start,io:meter.snapshot()};if(n>= (remove?0:5))samples.push(sample);fs.rmSync(d,{recursive:true});
 }return{label,fixture:remove?'64 files / 8 MiB assets':size?'20 users / 200 sessions':'1 user / 1 session',...summary(samples),raw:samples};}
async function ipc(child,operation){const id=Math.random().toString(36);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{child.off('message',read);reject(Error('meter timeout'));},5000);function read(m){if(m.nocturneIo===id){clearTimeout(timer);child.off('message',read);resolve(m.values);}}child.on('message',read);child.send({nocturneIo:operation,id});});}
async function apiCase(code,label){const d=path.join(work,'api-'+label);fs.mkdirSync(d);const port=await freePort(),base='http://127.0.0.1:'+port;let logs='';const child=fork(path.join(code,'server.js'),[],{env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:d,STATUS_INTERVAL:'3600',DOCKER_SOCK:path.join(d,'no-docker.sock'),UV_THREADPOOL_SIZE:'16',NODE_OPTIONS:'--require='+path.join(__dirname,'io-meter.js')},silent:true});child.stdout.on('data',b=>{logs+=b});child.stderr.on('data',b=>{logs+=b});
 try{for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}const c=client(base),password='benchmark-only-password';assert.equal((await c.post('/api/setup',{name:'admin',password})).status,200);
 for(let n=0;n<5;n++)assert.equal((await c.post('/api/login',{name:'admin',password})).status,200);await new Promise(r=>setTimeout(r,2600));await ipc(child,'reset');const samples=[];
 for(let n=0;n<30;n++){const s=performance.now();assert.equal((await c.post('/api/login',{name:'admin',password})).status,200);samples.push({ms:performance.now()-s});}
 const immediate=await ipc(child,'read');await new Promise(r=>setTimeout(r,2600));const durable=await ipc(child,'read');return{label,endpoint:'known-device POST /api/login',...summary(samples),immediateNodeFileApi:immediate,eventualNodeFileApi:durable,raw:samples};
 }finally{child.kill('SIGKILL');await new Promise(r=>child.once('exit',r));fs.writeFileSync(path.join(OUT,'api-'+label+'.log'),logs);}}
(async()=>{
 const before=path.join(work,'before-retirement.js');fs.writeFileSync(before,execFileSync('git',['show','db3e51f:auth-store.js'],{cwd:ROOT}));const rc4=path.join(work,'rc4');fs.mkdirSync(rc4);const tar=path.join(work,'rc4.tar');fs.writeFileSync(tar,execFileSync('git',['archive','f516629'],{cwd:ROOT,maxBuffer:64<<20}));execFileSync('tar',['-xf',tar,'-C',rc4]);
 const core=[];for(const [code,label] of [[before,'before-retirement'],[path.join(ROOT,'auth-store.js'),'current']])for(const [size,remove,name] of [[false,false,'small'],[true,false,'typical'],[true,true,'delete-8MiB']])core.push(storeCase(code,label+'-'+name,size,remove));
 const api=[await apiCase(rc4,'rc4'),await apiCase(ROOT,'current')];fs.writeFileSync(path.join(OUT,'auth-io-benchmark.json'),JSON.stringify({platform:process.platform,arch:process.arch,node:process.version,note:'Node API counts, not physical disk IOPS; VM storage, not NAS measurements; RC4 sessions may persist after API response',core,api},null,2)+'\n');console.log(JSON.stringify({core:core.map(({raw,...r})=>r),api:api.map(({raw,...r})=>r)},null,2));
})().catch(e=>{console.error(e.stack);process.exitCode=1;}).finally(()=>fs.rmSync(work,{recursive:true,force:true}));
